const LEVEL_SELECTION_REQUEST = 'LEVEL_SELECTION_REQUEST'
const LEVEL_SELECTION_FAILED = 'LEVEL_SELECTION_FAILED'
const LEVEL_SELECTION_SUCCESS = 'LEVEL_SELECTION_SUCCESS'

const TOGGLE_FLAG_SWITCH_REQUEST = 'TOGGLE_FLAG_SWITCH_REQUEST'
const TOGGLE_FLAG_SWITCH_DONE = 'TOGGLE_FLAG_SWITCH_DONE'

const INIT_BOARD_REQUEST = 'INIT_BOARD_REQUEST'
const INIT_BOARD_DONE = 'INIT_BOARD_DONE'

const GAME_OVER_STATE_REQUEST = 'GAME_OVER_STATE_REQUEST'
const GAME_OVER_STATE_DONE = 'GAME_OVER_STATE_DONE'

const CLEAR_GAME_REQUEST = 'CLEAR_GAME_REQUEST'
const CLEAR_GAME_DONE = 'CLEAR_GAME_DONE'

export {
    LEVEL_SELECTION_REQUEST,
    LEVEL_SELECTION_FAILED,
    LEVEL_SELECTION_SUCCESS,

    TOGGLE_FLAG_SWITCH_REQUEST,
    TOGGLE_FLAG_SWITCH_DONE,

    GAME_OVER_STATE_REQUEST,
    GAME_OVER_STATE_DONE,
    
    CLEAR_GAME_REQUEST,
    CLEAR_GAME_DONE,

    INIT_BOARD_DONE,
    INIT_BOARD_REQUEST
}